### ISSUE TITLE
🚀 Feature: <security policy>

### ISSUE THREAD

**Issue by CBID2** [OpenContributionsProject/opencontributionssite#102]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Hi @JoshuaKGoldberg and @blackgirlbytes! :) 
I noticed that there has not been a Security policy for this project. Since this repo is dedicated to the corporate sector and that open source is known for being secure, I think adding this policy would help leaders see that this project upholds this standard.

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for the suggestion! I don't know that we _need_ a security policy. We're just a static documentation site right now. Is this a thing many other static site projects do?

**Comment by CBID2** [comment]
> Hey thanks for the suggestion! I don't know that we _need_ a security policy. We're just a static documentation site right now. Is this a thing many other static site projects do?

I'm not too sure.🤔 I'll ask around :)

**Comment by blackgirlbytes** [comment]
I've done a bit of research on adding a security policy to our project, and my concern is that it will add unnecessary complexity. I don't think we're going to get a ton of like cross-site scripting or cross-site request forgery because there are no API calls, no backend, and no sensitive user data. 

I want to keep this site approachable and not scary for beginner developers. However, if our project gains more complexity, we may need to implement a security policy. Would you all be okay with me closing this issue? Maybe we can give it a label like `future-ideas` that we can go back to? But I want to make sure we are able to manage all the open issues and repos as Josh manages a lot of repos and I have a lot of work myself.

@CBID2 @JoshuaKGoldberg  What do you think?

**Comment by CBID2** [comment]
> I've done a bit of research on adding a security policy to our project, and my concern is that it will add unnecessary complexity. I don't think we're going to get a ton of like cross-site scripting or cross-site request forgery because there are no API calls, no backend, and no sensitive user data. 
> 
> 
> 
> I want to keep this site approachable and not scary for beginner developers. However, if our project gains more complexity, we may need to implement a security policy. Would you all be okay with me closing this issue? Maybe we can give it a label like `future-ideas` that we can go back to? But I want to make sure we are able to manage all the open issues and repos as Josh manages a lot of repos and I have a lot of work myself.
> 
> 
> 
> @CBID2 @JoshuaKGoldberg  What do you think? 

I agree with you @blackgirlbytes.

**Comment by JoshuaKGoldberg** [comment]
SGTM!
